services:
  backend:
    image: node:18
    container_name: tictactoe-backend
    working_dir: /app
    volumes:
      - ./server:/app
    ports:
      - "3000:3000"
    command: >
      sh -c "npm install && node server.js"
    environment:
      - NODE_ENV=development
    restart: unless-stopped