services:
  app:
    image: node:latest
    container_name: "tictactoe-app"
    ports:
      - "3000:3000"
    environment:
      - SERVER_PORT=3000
    volumes:
      - ./app:/app
    restart: unless-stopped
    command: sh -c "cd /app && npm install && node server.js"